from setuptools import setup, find_packages

setup(
    name="trading_model",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        'numpy>=1.21.0',
        'pandas>=1.3.0',
        'yfinance>=0.2.0',
        'ta-lib>=0.4.24',
        'scikit-learn>=1.0.0',
        'matplotlib>=3.4.0',
        'pytest>=7.0.0',
        'python-dotenv>=0.19.0',
        'ccxt>=2.0.0',
        'backtrader>=1.9.76.123',
        'google-generativeai>=0.3.0',
        'newsapi-python>=0.2.7',
        'beautifulsoup4>=4.9.3',
        'requests>=2.26.0',
        'plotly>=5.3.1',
        'nltk>=3.6.3',
        'textblob>=0.15.3',
    ],
    author="jaycode0101",
    description="A personal quant engineering lab for research, backtesting, and trading-system experiments",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/jaycode0101/nexus-quant-architecture",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.11",
) 
